# 환경변수로 제공되는 정보
# - HOST_USER_NAME: 실행계정 이름
# - HOST_USER_HOME: 실행계정 홈 디렉토리
# - HOST_UID: 실행계정 UID (User ID)
# - HOST_GID: 실행계정 GIU (Group ID)
# - HOST_TIMEZONE: 호스트 Timezone
# - IMAGE_TAG: 'docker image' Tag
services:
  service:  
    image: ${build.name}:${IMAGE_TAG:-latest}
    container_name: ${build.name}
    # 컨테이너 프로세스를 호스트 사용자의 권한으로 실행하도록 지정
    user: "${HOST_UID}:${HOST_GID}"
    extra_hosts:
      # 'host-gateway'는 'docker bridge' 네트워크의 Gateway IP 를 갖는 '도메인' 정보를 '${docker-extra_hosts-host_gateway}'으로 설정함.
      - ${docker-extra_hosts-host_gateway}:host-gateway
    ports:
      - "${server.port}:${server.port}"
    volumes: # host path : container path
      - ${log.dir}:/log/${group}/${build.name}
      - ${install.dir}/config:/app/${group}/${build.name}/config
    environment:
      # 실행계정 이름
      - USER=${HOST_USER_NAME}
      # 실행계정 홈 디렉토리
      - HOME=${HOST_USER_HOME}
      # 실행계정 UID
      - HOST_UID=${HOST_UID}
      # 실행계정 GID
      - HOST_GID=${HOST_GID}
      # 호스트 타임 존
      - TZ=${HOST_TIMEZONE}
      # 호스트 로케일 정보를 JVM 런타임 환경에 주입
      - LANG=${HOST_LANG}
      - LC_ALL=${HOST_LANG}
    restart: unless-stopped
